### ISSUE TITLE
Add null safety support

### ISSUE THREAD

**Issue by behnamsattar** [hathibelagal-dev/path_morph_for_flutter#2]

**Comment by behnamsattar** [comment]
@hathibelagal-dev is this package still maintained?

**Comment by ivofernandes** [comment]
I have fixed the null safety, I can upload it if you still want

**Comment by hathibelagal-dev** [comment]
Sorry for the very late response, but this is now fixed, along with Dart 3 compatibility.

`path_morph: ^1.1.0`
